[project]
name = "habits-trends"
version = "0.1.0"
description = "Exploring trends in my habits"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "marimo[recommended]>=0.9.27",
    "pandas>=2.2.3",
    "pyarrow>=18.1.0",
]
